name: Build and Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  check-tag:
    name: Check build tag
    runs-on: ubuntu-latest
    outputs:
        releaseExists: ${{ steps.check-tag.outputs.exists }}
        version: 'v${{ steps.get-version.outputs.version }}'
    steps:
      - uses: actions/checkout@v4

      - name: Get Library Project version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3.2
        with:
          path: ./projects/ez-ui/

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: 'v${{ steps.get-version.outputs.version }}'

  build:
    name: Build
    needs: check-tag
    if: needs.check-tag.outputs.releaseExists == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26.4.0
          registry-url: https://registry.npmjs.org/

      - name: Install Angular CLI
        run: npm i @angular/cli -g

      - name: Install dependencies
        run: npm i

      - name: Build package
        run: ng build @kris701/ez-ui

      - name: Archive dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/ez-ui

  publish-npm:
    name: Publish (NPM)
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26.4.0
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Download dist
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: ./dist/ez-ui

      - name: Publish Package
        run: |
            cd ./dist/ez-ui
            npm publish --access public

  publish-github:
    name: Publish (Github)
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26.4.0
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kris701'

      - name: Download dist
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: ./dist/ez-ui

      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            cd ./dist/ez-ui
            npm publish --access public

  publish-local:
    name: Create Github Release
    needs: [build, check-tag]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26.4.0
          registry-url: https://registry.npmjs.org/

      - name: Download dist
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: ./dist/ez-ui

      - name: Pack package (for Git release)
        run: npm pack ./dist/ez-ui/

      - name: Create Tag
        continue-on-error: true
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ needs.check-tag.outputs.version }}
          message: "Latest release"

      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          artifacts: "*.tgz"
          tag: ${{ needs.check-tag.outputs.version }}
          generateReleaseNotes: true
